CREATE DATABASE CI_CD
ALTER DATABASE CI_CD COLLATE Latin1_General_CI_AI
GO 
USE CI_CD
GO
CREATE SCHEMA GEN
GO
CREATE TABLE GEN.Varios(
 Grupo VARCHAR(100) NOT NULL,
 Codigo VARCHAR(50) NOT NULL,
 Descripcion VARCHAR(100) NOT NULL,
 CONSTRAINT PK_Varios_GrupoCodigo PRIMARY KEY(Grupo,Codigo)
)
GO
CREATE TABLE GEN.UnidadMedida(
	Id INT IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	Abreviacion VARCHAR(20) NOT NULL,
	CONSTRAINT PK_UnidadMedida_Id PRIMARY KEY(Id)
)
GO
CREATE TABLE GEN.Marca(
 Id INT IDENTITY(1,1) NOT NULL,
 Nombre VARCHAR(100) NOT NULL,
 Descripcion VARCHAR(MAX) NULL,
 CONSTRAINT PK_Marca_Id PRIMARY KEY(Id)
)
GO
CREATE TABLE GEN.Categoria(
 Id INT IDENTITY(1,1) NOT NULL,
 Nombre VARCHAR(100) NOT NULL,
 Descripcion VARCHAR(MAX) NULL,
 CONSTRAINT PK_Categoria_Id PRIMARY KEY(Id)
)
GO
CREATE TABLE GEN.Cargo(
 Id INT IDENTITY(1,1) NOT NULL,
 Nombre VARCHAR(100) NOT NULL,
 Descripcion VARCHAR(MAX) NULL,
 CONSTRAINT PK_Cargo_Id PRIMARY KEY(Id)
)
GO 
CREATE TABLE GEN.Producto(
 Id INT IDENTITY(1,1) NOT NULL,
 Codigo VARCHAR(50) NOT NULL,
 Nombre VARCHAR(200) NOT NULL,
 PrecioVenta DECIMAL(18,2) NOT NULL,
 StockMinimo INT NOT NULL,
 IdUnidadMedida INT NOT NULL,
 IdMarca INT NOT NULL,
 IdCategoria INT NOT NULL,
 Estado INT NOT NULL,
 CONSTRAINT PK_Producto_Id PRIMARY KEY(Id),
 CONSTRAINT FK_Producto_IdUnidadMedida FOREIGN KEY(IdUnidadMedida) REFERENCES GEN.UnidadMedida(Id),
 CONSTRAINT FK_Producto_IdMarca FOREIGN KEY(IdMarca) REFERENCES GEN.Marca(Id),
 CONSTRAINT FK_Producto_IdCategoria FOREIGN KEY(IdCategoria) REFERENCES GEN.Categoria(Id),
 CONSTRAINT CH_Producto_Estado CHECK(Estado = 1 OR Estado = 2)
)
GO
CREATE TABLE GEN.Empleado(
 Id INT IDENTITY(1,1) NOT NULL,
 Nombre VARCHAR(50) NOT NULL,
 ApellidoPaterno VARCHAR(50) NOT NULL,
 ApellidoMaterno VARCHAR(50) NOT NULL,
 FechaNacimiento DATE NOT NULL,
 TipoDocumentoIdentidad INT NOT NULL,
 DocumentoIdentidad VARCHAR(50) NOT NULL,
 Sexo CHAR(1) NOT NULL,
 EstadoCivil INT NOT NULL,
 Telefono VARCHAR(20) NULL,
 Correo VARCHAR(50) NULL,
 Direccion VARCHAR(MAX) NULL,
 HaberBasico DECIMAL(18,2) NOT NULL,
 IdCargo INT NOT NULL,
 CONSTRAINT PK_Empleado_Id PRIMARY KEY(Id),
 CONSTRAINT FK_Empleado_IdCargo FOREIGN KEY(IdCargo) REFERENCES GEN.Cargo(Id)
)
GO
CREATE TABLE GEN.Cliente(
 Id INT IDENTITY(1,1) NOT NULL,
 TipoCliente INT NOT NULL,
 Nombre VARCHAR(100) NOT NULL,
 Documento VARCHAR(50) NULL,
 Telefono VARCHAR(50) NULL,
 Correo VARCHAR(100) NULL,
 Direccion VARCHAR(MAX) NULL,
 NombreContacto VARCHAR(100) NULL,
 TelefonoContacto VARCHAR(50) NULL,
 CorreoContacto VARCHAR(100) NULL,
 Estado INT NOT NULL,
 CONSTRAINT PK_Cliente_Id PRIMARY KEY(Id),
 CONSTRAINT CH_Cliente_Estado CHECK(Estado = 1 OR Estado = 2),
 CONSTRAINT CH_Cliente_TipoCliente CHECK(TipoCliente = 1 OR TipoCliente = 2)
)


ALTER TABLE GEN.Empleado ADD CONSTRAINT PK_Empleado_Id PRIMARY KEY(Id)